CREATE TYPE pricing_rule_kind AS ENUM ('PLATFORM_FEE','PAYMENT_FEE','SELLER_FEE','SHIPPING_MARGIN');
CREATE TYPE ledger_transaction_type AS ENUM ('ORDER_PAYMENT','PROMOTION_PURCHASE','SUBSCRIPTION_PURCHASE','ADVERTISING_PURCHASE','PAYOUT','REFUND','REVERSAL');
CREATE TYPE wallet_entry_status AS ENUM ('PENDING','AVAILABLE','WITHDRAWN','HELD','REFUNDED');
CREATE TYPE payout_status AS ENUM ('REQUESTED','PROCESSING','COMPLETED','FAILED','CANCELLED');

CREATE TABLE pricing_rules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code TEXT NOT NULL UNIQUE, kind pricing_rule_kind NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'VND', status TEXT NOT NULL CHECK(status IN ('ACTIVE','INACTIVE')), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE pricing_versions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), rule_id UUID NOT NULL REFERENCES pricing_rules(id), rate_bps INTEGER NOT NULL CHECK(rate_bps BETWEEN 0 AND 10000), fixed_amount BIGINT NOT NULL DEFAULT 0 CHECK(fixed_amount>=0), effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ, created_by UUID REFERENCES users(id), reason TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(effective_to IS NULL OR effective_to>effective_from));
CREATE UNIQUE INDEX pricing_versions_active_range ON pricing_versions(rule_id,effective_from);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS pricing_version_id UUID REFERENCES pricing_versions(id), ADD COLUMN IF NOT EXISTS platform_fee_rate_bps_snapshot INTEGER NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS platform_fee_amount BIGINT NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS payment_fee_amount BIGINT NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS seller_payout_amount BIGINT NOT NULL DEFAULT 0;
CREATE TABLE ledger_transactions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), type ledger_transaction_type NOT NULL, order_id UUID REFERENCES orders(id), payment_id UUID REFERENCES payments(id), reference_id UUID, idempotency_key TEXT UNIQUE, status TEXT NOT NULL CHECK(status IN ('PENDING','FINALIZED','REVERSED')), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), finalized_at TIMESTAMPTZ);
CREATE TABLE ledger_entries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), transaction_id UUID NOT NULL REFERENCES ledger_transactions(id), account_code TEXT NOT NULL, amount BIGINT NOT NULL CHECK(amount<>0), currency CHAR(3) NOT NULL DEFAULT 'VND', user_id UUID REFERENCES users(id), order_id UUID REFERENCES orders(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX ledger_entries_transaction_idx ON ledger_entries(transaction_id); CREATE INDEX ledger_entries_order_idx ON ledger_entries(order_id);
CREATE TABLE seller_wallets (seller_id UUID PRIMARY KEY REFERENCES users(id), pending_balance BIGINT NOT NULL DEFAULT 0 CHECK(pending_balance>=0), available_balance BIGINT NOT NULL DEFAULT 0 CHECK(available_balance>=0), held_balance BIGINT NOT NULL DEFAULT 0 CHECK(held_balance>=0), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE wallet_transactions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), seller_id UUID NOT NULL REFERENCES users(id), order_id UUID REFERENCES orders(id), ledger_transaction_id UUID NOT NULL REFERENCES ledger_transactions(id), status wallet_entry_status NOT NULL, amount BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE payouts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), seller_id UUID NOT NULL REFERENCES users(id), amount BIGINT NOT NULL CHECK(amount>0), fee BIGINT NOT NULL DEFAULT 0 CHECK(fee>=0), net_amount BIGINT NOT NULL CHECK(net_amount>=0), idempotency_key TEXT NOT NULL UNIQUE, status payout_status NOT NULL DEFAULT 'REQUESTED', requested_at TIMESTAMPTZ NOT NULL DEFAULT now(), processed_at TIMESTAMPTZ);
CREATE TABLE idempotency_keys (key TEXT PRIMARY KEY, actor_id UUID REFERENCES users(id), request_hash TEXT NOT NULL, response JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), expires_at TIMESTAMPTZ NOT NULL);
