'use client';
import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, Plus, Settings2 } from 'lucide-react';
import { Field, ListingCategory, ListingError, Template, fieldTypes, listingRequest, priceLabels } from '../../lib/listings';
import { validateTemplate } from '../../../backend/src/listings/listing-domain';

export function TemplateAdmin() {
  const [categories,setCategories]=useState<ListingCategory[]>([]),[categoryId,setCategoryId]=useState('');
  const [template,setTemplate]=useState<Template|null>(null),[reason,setReason]=useState('');
  const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const [newName,setNewName]=useState(''),[newSlug,setNewSlug]=useState('');
  const [invalidConfigs,setInvalidConfigs]=useState<Record<number,boolean>>({});
  useEffect(()=>{listingRequest<ListingCategory[]>('/listing-categories').then(setCategories).catch(error=>setError(error.message));},[]);
  useEffect(()=>{if(!categoryId)return;let active=true;setTemplate(null);setError('');setInvalidConfigs({});listingRequest<Template>(`/listing-templates/${categoryId}`).then(value=>{if(active)setTemplate(value);}).catch(error=>{if(!active)return;if(error instanceof ListingError&&error.status===404)setTemplate({id:'',categoryId,name:categories.find(item=>item.id===categoryId)?.name??'Biểu mẫu mới',version:0,fields:[],config:{priceModes:['FIXED','CONTACT','FREE']}});else setError(error.message);});return()=>{active=false;};},[categoryId,categories]);
  function field(index:number,patch:Partial<Field>){setTemplate(value=>value?{...value,fields:value.fields.map((item,i)=>i===index?{...item,...patch}:item)}:null);}
  function move(index:number,direction:number){if(!template)return;const fields=[...template.fields];[fields[index],fields[index+direction]]=[fields[index+direction],fields[index]];setTemplate({...template,fields});}
  async function save(){if(!template)return;setError('');setMessage('');if(Object.values(invalidConfigs).some(Boolean)){setError('Hãy sửa các cấu hình JSON chưa hợp lệ trước khi lưu.');return;}const problem=validateTemplate(template);if(problem){setError(problem);return;}if(reason.trim().length<3){setError('Nhập lý do thay đổi, tối thiểu 3 ký tự.');return;}setBusy(true);try{const result=await listingRequest<Template>(`/admin/listing-engine/templates/${categoryId}/versions`,'POST',{definition:{name:template.name,fields:template.fields,config:template.config,reason}});setTemplate(result);setReason('');setMessage(`Đã tạo phiên bản ${result.version}. Các bản nháp cũ giữ nguyên biểu mẫu.`);}catch(error){setError(error instanceof Error?error.message:'Không lưu được cấu hình.');}finally{setBusy(false);}}
  async function category(){setBusy(true);setError('');try{const result=await listingRequest<{id:string}>('/admin/listing-engine/categories','POST',{name:newName,slug:newSlug,...(categoryId?{parentId:categoryId}:{})});setCategories(await listingRequest<ListingCategory[]>('/listing-categories'));setCategoryId(result.id);setNewName('');setNewSlug('');setMessage('Đã tạo danh mục. Hãy thiết lập và lưu biểu mẫu.');}catch(error){setError(error instanceof Error?error.message:'Không tạo được danh mục.');}finally{setBusy(false);}}
  return <main className="lf-page"><div className="lf-heading"><div><p className="lf-eyebrow">QUẢN TRỊ · FORM ENGINE</p><h1>Biểu mẫu đăng tin</h1><p>Thay đổi cấu hình, không cần sửa giao diện của từng danh mục.</p></div><Settings2 size={30}/></div><section className="lf-panel">
    <div className="lf-callout">Chỉ tài khoản quản trị có quyền lưu. Mỗi lần lưu tạo phiên bản mới và ghi nhật ký; không thay đổi dữ liệu lịch sử.</div>
    {error&&<div role="alert" className="lf-alert">{error}</div>}{message&&<div role="status" className="lf-callout">{message}</div>}
    <fieldset className="lf-fieldset" disabled={busy}><div className="lf-field"><label htmlFor="admin-category">Danh mục</label><select id="admin-category" value={categoryId} onChange={event=>setCategoryId(event.target.value)}><option value="">Chọn danh mục</option>{categories.map(item=><option key={item.id} value={item.id}>{item.isGroup?'▸ ':''}{item.name}</option>)}</select></div>
    <details><summary>Tạo danh mục mới</summary><p>Danh mục mới nằm trong danh mục đang chọn; để trống lựa chọn để tạo nhóm gốc.</p><div className="lf-fields-grid"><div className="lf-field"><label htmlFor="admin-new-name">Tên</label><input id="admin-new-name" value={newName} maxLength={100} onChange={event=>setNewName(event.target.value)}/></div><div className="lf-field"><label htmlFor="admin-new-slug">Mã không dấu, cách bằng gạch nối</label><input id="admin-new-slug" value={newSlug} maxLength={120} onChange={event=>setNewSlug(event.target.value)}/></div></div><button type="button" className="lf-secondary" onClick={category}>Tạo danh mục</button></details>
    {template&&<><h2 style={{marginTop:30}}>Phiên bản {template.version||'mới'}</h2><div className="lf-field"><label htmlFor="admin-template-name">Tên biểu mẫu</label><input id="admin-template-name" value={template.name} maxLength={150} onChange={event=>setTemplate({...template,name:event.target.value})}/></div><div className="lf-options">{Object.entries(priceLabels).map(([mode,label])=><label key={mode} className="lf-check"><input type="checkbox" checked={template.config.priceModes.includes(mode)} onChange={event=>setTemplate({...template,config:{priceModes:event.target.checked?[...template.config.priceModes,mode]:template.config.priceModes.filter(item=>item!==mode)}})}/>{label}</label>)}</div>
      {template.fields.map((item,index)=><details key={index} className="lf-admin-field"><summary>{index+1}. {item.label||'Trường mới'} · {item.type} {item.enabled?'':'(đã tắt)'}</summary><div className="lf-media-actions"><button type="button" className="lf-secondary" disabled={index===0} onClick={()=>move(index,-1)}><ArrowUp size={16}/>Lên</button><button type="button" className="lf-secondary" disabled={index===template.fields.length-1} onClick={()=>move(index,1)}><ArrowDown size={16}/>Xuống</button><label className="lf-check"><input type="checkbox" checked={item.enabled} onChange={event=>field(index,{enabled:event.target.checked})}/>Bật</label><label className="lf-check"><input type="checkbox" checked={item.required} onChange={event=>field(index,{required:event.target.checked})}/>Bắt buộc</label></div>
        <div className="lf-fields-grid"><div className="lf-field"><label htmlFor={`admin-key-${index}`}>Mã trường</label><input id={`admin-key-${index}`} value={item.key} maxLength={64} onChange={event=>field(index,{key:event.target.value})}/></div><div className="lf-field"><label htmlFor={`admin-label-${index}`}>Nhãn hiển thị</label><input id={`admin-label-${index}`} value={item.label} maxLength={150} onChange={event=>field(index,{label:event.target.value})}/></div><div className="lf-field"><label htmlFor={`admin-type-${index}`}>Kiểu dữ liệu</label><select id={`admin-type-${index}`} value={item.type} onChange={event=>field(index,{type:event.target.value as Field['type']})}>{fieldTypes.map(type=><option key={type}>{type}</option>)}</select></div><div className="lf-field"><label htmlFor={`admin-unit-${index}`}>Đơn vị</label><input id={`admin-unit-${index}`} value={item.config.unit??''} onChange={event=>field(index,{config:{...item.config,unit:event.target.value}})}/></div></div>
        <OptionsEditor key={'options-'+template.id+'-'+item.key} field={item} onChange={options=>field(index,{options})}/>
        <ConfigEditor key={'config-'+template.id+'-'+item.key+'-'+(item.config.unit??'')} field={item} onChange={config=>field(index,{config})} onValidity={valid=>setInvalidConfigs(values=>({...values,[index]:!valid}))}/>
      </details>)}
      <button type="button" className="lf-secondary" disabled={template.fields.length>=80} onClick={()=>setTemplate({...template,fields:[...template.fields,{key:`field_${crypto.randomUUID().slice(0,8)}`,label:'Trường mới',type:'text',required:false,enabled:true,options:[],config:{}}]})}><Plus size={16}/>Thêm trường</button>
      <div className="lf-field" style={{marginTop:24}}><label htmlFor="admin-reason">Lý do thay đổi *</label><textarea id="admin-reason" maxLength={500} value={reason} onChange={event=>setReason(event.target.value)}/></div><button type="button" className="lf-primary" onClick={save}>{busy?'Đang lưu…':'Lưu phiên bản mới'}</button>
    </>}</fieldset></section></main>;
}

function OptionsEditor({field,onChange}:{field:Field;onChange:(options:Field['options'])=>void}){
  const [raw,setRaw]=useState(field.options.map(item=>item.value+' | '+item.label).join('\n'));
  return <div className="lf-field"><label>Tùy chọn (mỗi dòng: giá trị | nhãn)<textarea aria-label={`Tùy chọn ${field.label}`} rows={4} value={raw} onChange={event=>{const value=event.target.value;setRaw(value);onChange(value.split('\n').filter(line=>line.trim()).map(line=>{const [value,...label]=line.split('|');return {value:value.trim(),label:label.join('|').trim()||value.trim()};}));}}/></label></div>;
}
function ConfigEditor({field,onChange,onValidity}:{field:Field;onChange:(config:Field['config'])=>void;onValidity:(valid:boolean)=>void}){
  const [raw,setRaw]=useState(JSON.stringify(field.config,null,2)),[error,setError]=useState('');
  return <div className="lf-field"><label>Kiểm tra & điều kiện hiển thị (JSON)<textarea aria-label={`Cấu hình ${field.label}`} rows={5} value={raw} onChange={event=>{const value=event.target.value;setRaw(value);try{const parsed=JSON.parse(value);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error();onChange(parsed);onValidity(true);setError('');}catch{onValidity(false);setError('JSON chưa hợp lệ. Hãy sửa trước khi lưu.');}}}/></label><small>Hỗ trợ min, max, minLength, maxLength, placeholder, help, unit và visibleWhen: field / operator (eq, ne, in) / value. Điều kiện chỉ tham chiếu trường đứng trước.</small>{error&&<small className="lf-error">{error}</small>}</div>;
}
