package com.tattantat.app.presentation.sell

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.layout.ContentScale
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import com.tattantat.app.domain.product.Product
import com.tattantat.app.presentation.home.ProductCard
import coil.compose.AsyncImage

@Composable fun SellScreen(onMyListings: () -> Unit, vm: SellViewModel = hiltViewModel()) { val form by vm.form.collectAsState();var choosingCategory by remember{mutableStateOf(false)};var choosingCondition by remember{mutableStateOf(false)}; val picker = rememberLauncherForActivityResult(ActivityResultContracts.GetMultipleContents()) { vm.addImages(it) }; if (form.published) { PublishSuccess(onMyListings); return }; Column(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { Text("Đăng bán", style = MaterialTheme.typography.headlineSmall); Text("Đăng tin nhanh trong vài bước"); OutlinedButton(onClick = { picker.launch("image/*") }) { Text("+ Chọn ảnh sản phẩm (${form.images.size}/10)") }; if(form.images.isNotEmpty()){Text("Đã chọn ${form.images.size} ảnh; chạm Bỏ để xóa ảnh không dùng.",style=MaterialTheme.typography.bodySmall);LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(form.images,key={it.toString()}){uri->Column{AsyncImage(uri,"Ảnh đã chọn",Modifier.size(92.dp),contentScale=ContentScale.Crop);TextButton(onClick={vm.removeImage(uri)}){Text("Bỏ")}}}}}; Field(form.title, { vm.update { f -> f.copy(title = it) } }, "Tên sản phẩm"); Field(form.price, { vm.update { f -> f.copy(price = it.filter(Char::isDigit)) } }, "Giá (đ)", KeyboardType.Number); OutlinedButton(onClick={choosingCategory=true},enabled=form.categories.isNotEmpty()){Text("Danh mục: ${form.category}")}; OutlinedButton(onClick={choosingCondition=true}){Text("Tình trạng: ${form.condition}")}; OutlinedTextField(form.description, { vm.update { f -> f.copy(description = it) } }, Modifier.fillMaxWidth().height(110.dp), label = { Text("Mô tả ngắn") }); form.error?.let { Text(it, color = MaterialTheme.colorScheme.error) }; Button(onClick = vm::publish, enabled = !form.loading && form.title.isNotBlank() && form.price.isNotBlank() && form.categoryId != null, modifier = Modifier.fillMaxWidth()) { Text(if (form.loading) "Đang đăng..." else "Đăng bán") }; TextButton(onClick = onMyListings, modifier = Modifier.fillMaxWidth()) { Text("Xem tin đăng của tôi") } };if(choosingCategory)AlertDialog(onDismissRequest={choosingCategory=false},title={Text("Chọn danh mục")},text={Column{form.categories.forEach{category->TextButton(onClick={vm.selectCategory(category);choosingCategory=false},modifier=Modifier.fillMaxWidth()){Text(category.name)}}}},confirmButton={});if(choosingCondition)AlertDialog(onDismissRequest={choosingCondition=false},title={Text("Chọn tình trạng")},text={Column{listOf("NEW" to "Mới", "LIKE_NEW" to "Gần như mới", "USED_GOOD" to "Đã sử dụng tốt", "USED_FAIR" to "Đã sử dụng", "FOR_PARTS" to "Linh kiện / cần sửa").forEach{(code,label)->TextButton(onClick={vm.selectCondition(code,label);choosingCondition=false},modifier=Modifier.fillMaxWidth()){Text(label)}}}},confirmButton={}) }
@Composable private fun PublishSuccess(onMyListings: () -> Unit) = Column(Modifier.fillMaxSize().padding(24.dp), verticalArrangement = Arrangement.Center) { Text("Đăng bán thành công!", style = MaterialTheme.typography.headlineSmall, color = MaterialTheme.colorScheme.primary); Text("Tin của bạn đang chờ được hiển thị.", modifier = Modifier.padding(vertical = 12.dp)); Button(onClick = onMyListings, modifier = Modifier.fillMaxWidth()) { Text("Xem tin đăng của tôi") } }
@Composable fun MyListingsScreen(onPromote:(String)->Unit={},onAdvertise:(String)->Unit={},onEdit:(String)->Unit={},vm: MyListingsViewModel = hiltViewModel()) { val state by vm.state.collectAsState(); Column(Modifier.fillMaxSize().padding(16.dp)) { Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Tin đăng của tôi", style = MaterialTheme.typography.headlineSmall);TextButton(onClick=vm::refresh,enabled=!state.loading){Text("Làm mới")}}; Spacer(Modifier.height(12.dp)); when { state.loading -> CircularProgressIndicator(); state.error!=null -> Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text(state.error!!,color=MaterialTheme.colorScheme.error);Button(onClick=vm::refresh){Text("Thử lại")}}; state.items.isEmpty() -> Text("Bạn chưa có tin đăng nào. Hãy tạo tin đầu tiên từ mục Đăng bán."); else -> state.items.forEach { item -> ProductCard(item); val statusText=when(item.status){"HIDDEN"->"Đang ẩn – người mua không thể thấy tin này";"RESERVED"->"Đã có người đặt – đang xử lý đơn hàng";"SOLD"->"Đã bán";else->"Đang hiển thị"}; Text(statusText,style=MaterialTheme.typography.bodySmall,color=if(item.status=="ACTIVE") MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.error); Row{if(item.status=="ACTIVE"||item.status=="HIDDEN")TextButton(onClick={onEdit(item.id)}){Text("Chỉnh sửa")};TextButton(onClick={onPromote(item.id)},enabled=item.status=="ACTIVE"){Text("Đẩy tin / VIP")};TextButton(onClick={onAdvertise(item.id)},enabled=item.status=="ACTIVE"){Text("Quảng cáo")};if(item.status=="ACTIVE"||item.status=="HIDDEN")TextButton(onClick={vm.setVisibility(item.id,if(item.status=="HIDDEN") "ACTIVE" else "HIDDEN")}){Text(if(item.status=="HIDDEN") "Hiện tin" else "Ẩn tin")}} } } } }
@Composable private fun Field(value: String, update: (String) -> Unit, label: String, type: KeyboardType = KeyboardType.Text) = OutlinedTextField(value, update, Modifier.fillMaxWidth(), label = { Text(label) }, singleLine = true, keyboardOptions = androidx.compose.foundation.text.KeyboardOptions(keyboardType = type))
