// Danh mục chính và danh mục con - đồng bộ từ web/lib/marketplace.ts (CATEGORY_ENGINE_TAXONOMY). Slug dùng để tìm tin qua categorySlug.
export type TaxSub = { slug: string; name: string };
export type TaxCategory = { slug: string; label: string; short: string; icon: number; subs: TaxSub[] };

export const TAXONOMY: TaxCategory[] = [
  { slug: 'bat-dong-san', label: 'Nhà đất', short: 'Nhà đất', icon: require('../../assets/category-icons/nha-dat.png'), subs: [
    { slug: 'ban-nha', name: 'Bán nhà' },
    { slug: 'ban-dat', name: 'Bán đất' },
    { slug: 'can-ho', name: 'Căn hộ / Chung cư' },
    { slug: 'phong-tro', name: 'Phòng trọ' },
    { slug: 'cho-thue-nha', name: 'Cho thuê nhà' },
    { slug: 'cho-thue-mat-bang', name: 'Cho thuê mặt bằng' },
    { slug: 'van-phong', name: 'Văn phòng' },
    { slug: 'bat-dong-san-khac', name: 'BĐS khác' },
  ] },
  { slug: 'xe-co', label: 'Xe cộ', short: 'Xe cộ', icon: require('../../assets/category-icons/xe-co.png'), subs: [
    { slug: 'o-to', name: 'Ô tô' },
    { slug: 'xe-may', name: 'Xe máy' },
    { slug: 'xe-dien', name: 'Xe điện' },
    { slug: 'xe-tai', name: 'Xe tải' },
    { slug: 'xe-ban-tai', name: 'Xe bán tải' },
    { slug: 'xe-dap', name: 'Xe đạp' },
    { slug: 'phu-tung-xe', name: 'Phụ tùng & Phụ kiện xe' },
  ] },
  { slug: 'do-cong-nghe', label: 'Đồ công nghệ', short: 'Công nghệ', icon: require('../../assets/category-icons/do-cong-nghe.png'), subs: [
    { slug: 'dien-thoai', name: 'Điện thoại' },
    { slug: 'laptop', name: 'Laptop' },
    { slug: 'may-tinh-bang', name: 'Máy tính bảng' },
    { slug: 'may-tinh-de-ban', name: 'Máy tính để bàn' },
    { slug: 'may-anh', name: 'Máy ảnh' },
    { slug: 'tv', name: 'TV' },
    { slug: 'thiet-bi-am-thanh', name: 'Thiết bị âm thanh' },
    { slug: 'phu-kien-cong-nghe', name: 'Phụ kiện công nghệ' },
    { slug: 'may-choi-game', name: 'Máy chơi game' },
    { slug: 'dong-ho-thong-minh', name: 'Đồng hồ thông minh' },
  ] },
  { slug: 'do-gia-dung', label: 'Nhà cửa & Đời sống', short: 'Nhà cửa', icon: require('../../assets/category-icons/nha-cua-doi-song.png'), subs: [
    { slug: 'sofa', name: 'Sofa' },
    { slug: 'ban-ghe', name: 'Bàn ghế' },
    { slug: 'tu', name: 'Tủ' },
    { slug: 'giuong', name: 'Giường' },
    { slug: 'tu-lanh', name: 'Tủ lạnh' },
    { slug: 'may-giat', name: 'Máy giặt' },
    { slug: 'dieu-hoa', name: 'Điều hòa' },
    { slug: 'thiet-bi-nha-bep', name: 'Thiết bị nhà bếp' },
  ] },
  { slug: 'thoi-trang', label: 'Thời trang & Cá nhân', short: 'Thời trang', icon: require('../../assets/category-icons/thoi-trang-ca-nhan.png'), subs: [
    { slug: 'quan-ao', name: 'Quần áo' },
    { slug: 'giay-dep', name: 'Giày dép' },
    { slug: 'tui-xach', name: 'Túi xách' },
    { slug: 'thoi-trang-dong-ho', name: 'Đồng hồ' },
    { slug: 'phu-kien-thoi-trang', name: 'Phụ kiện thời trang' },
  ] },
  { slug: 'me-va-be', label: 'Mẹ & Bé', short: 'Mẹ & Bé', icon: require('../../assets/category-icons/me-va-be.png'), subs: [
    { slug: 'quan-ao-tre-em', name: 'Quần áo trẻ em' },
    { slug: 'sua-do-an-cho-be', name: 'Sữa & đồ ăn cho bé' },
    { slug: 'xe-day-ghe-noi-cui', name: 'Xe đẩy, ghế, nôi, cũi' },
    { slug: 'do-choi-tre-em', name: 'Đồ chơi trẻ em' },
    { slug: 'do-cho-me', name: 'Đồ cho mẹ' },
    { slug: 'do-cho-be', name: 'Đồ dùng cho bé' },
    { slug: 'me-be-khac', name: 'Mẹ & bé khác' },
  ] },
  { slug: 'the-thao', label: 'Thể thao & Giải trí', short: 'Thể thao', icon: require('../../assets/category-icons/the-thao-giai-tri.png'), subs: [
    { slug: 'do-choi', name: 'Đồ chơi' },
    { slug: 'dung-cu-the-thao', name: 'Dụng cụ thể thao' },
    { slug: 'nhac-cu', name: 'Nhạc cụ' },
    { slug: 'playstation', name: 'Playstation' },
    { slug: 'xbox', name: 'Xbox' },
    { slug: 'nintendo', name: 'Nintendo' },
  ] },
  { slug: 'thu-cung', label: 'Thú cưng', short: 'Thú cưng', icon: require('../../assets/category-icons/thu-cung.png'), subs: [
    { slug: 'thu-cung-canh', name: 'Thú cưng' },
    { slug: 'phu-kien-thu-cung', name: 'Phụ kiện thú cưng' },
    { slug: 'thuc-an-thu-cung', name: 'Thức ăn thú cưng' },
  ] },
  { slug: 'dich-vu', label: 'Dịch vụ', short: 'Dịch vụ', icon: require('../../assets/category-icons/dich-vu.png'), subs: [
    { slug: 'sua-chua', name: 'Sửa chữa' },
    { slug: 'van-chuyen', name: 'Vận chuyển' },
    { slug: 'thiet-ke', name: 'Thiết kế' },
    { slug: 'cho-thue', name: 'Cho thuê' },
    { slug: 'dich-vu-ca-nhan', name: 'Dịch vụ cá nhân' },
    { slug: 'dich-vu-doanh-nghiep', name: 'Dịch vụ doanh nghiệp' },
  ] },
  { slug: 'thuc-pham', label: 'Thực phẩm', short: 'Thực phẩm', icon: require('../../assets/category-icons/thuc-pham.png'), subs: [
    { slug: 'do-an', name: 'Đồ ăn' },
    { slug: 'do-uong', name: 'Đồ uống' },
    { slug: 'dac-san', name: 'Đặc sản' },
    { slug: 'rau-cu-trai-cay', name: 'Rau củ / Trái cây' },
    { slug: 'thuc-pham-tuoi-song', name: 'Thực phẩm tươi sống' },
    { slug: 'thuc-pham-kho', name: 'Thực phẩm khô' },
    { slug: 'do-handmade', name: 'Đồ handmade' },
    { slug: 'thuc-pham-khac', name: 'Khác' },
  ] },
  { slug: 'may-moc-cong-nghiep', label: 'Máy móc & Công nghiệp', short: 'Máy móc', icon: require('../../assets/category-icons/may-moc-cong-nghiep.png'), subs: [
    { slug: 'may-moc-cong-nghiep', name: 'Máy móc công nghiệp' },
    { slug: 'may-moc-nong-nghiep', name: 'Máy móc nông nghiệp' },
    { slug: 'thiet-bi-xay-dung', name: 'Thiết bị xây dựng' },
    { slug: 'dung-cu-co-khi', name: 'Dụng cụ cơ khí' },
    { slug: 'thiet-bi-nha-hang', name: 'Thiết bị nhà hàng' },
    { slug: 'thiet-bi-cua-hang', name: 'Thiết bị cửa hàng' },
    { slug: 'thiet-bi-van-phong', name: 'Thiết bị văn phòng' },
    { slug: 'nguyen-vat-lieu', name: 'Nguyên vật liệu' },
    { slug: 'giong-cay-trong', name: 'Giống cây trồng' },
    { slug: 'may-moc-khac', name: 'Khác' },
  ] },
  { slug: 'tang-mien-phi', label: 'Tặng miễn phí', short: 'Tặng miễn phí', icon: require('../../assets/category-icons/tang-mien-phi.png'), subs: [
    { slug: 'do-gia-dung-tang', name: 'Đồ gia dụng tặng' },
    { slug: 'sach-quan-ao-tang', name: 'Sách & Quần áo tặng' },
    { slug: 'thu-cung-cho-nuoi', name: 'Thú cưng tặng nuôi' },
  ] },
  { slug: 'phan-mem-dich-vu-so', label: 'Phần mềm & Dịch vụ số', short: 'Phần mềm', icon: require('../../assets/category-icons/phan-mem-dich-vu-so.png'), subs: [
    { slug: 'phan-mem-quan-ly-ban-hang', name: 'Phần mềm quản lý bán hàng' },
    { slug: 'phan-mem-tien-ich', name: 'Phần mềm tiện ích' },
    { slug: 'thiet-ke-website', name: 'Thiết kế website' },
    { slug: 'thiet-ke-ung-dung', name: 'Thiết kế ứng dụng / Phần mềm theo yêu cầu' },
    { slug: 'ban-quyen-tai-khoan', name: 'Bản quyền & tài khoản số' },
    { slug: 'hosting-ten-mien', name: 'Hosting, tên miền & máy chủ' },
    { slug: 'marketing-online', name: 'Marketing & quảng cáo online' },
    { slug: 'tu-van-cai-dat-it', name: 'Tư vấn, cài đặt & hỗ trợ IT' },
    { slug: 'phan-mem-khac', name: 'Phần mềm & dịch vụ số khác' },
  ] },
  { slug: 'khac', label: 'Khác', short: 'Khác', icon: require('../../assets/category-icons/khac.png'), subs: [
    { slug: 'hang-hoa-khac', name: 'Sản phẩm khác' },
  ] },
];

export const findTaxonomy = (slug?: string) => TAXONOMY.find(c => c.slug === slug);
